name: photo_album
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.0.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.2.3
  image_picker: ^1.0.7
  rive: ^0.13.4
  internet_connection_checker_plus: ^2.7.1
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.4.0
  fluttertoast: ^8.2.12
  flutter_dotenv: ^5.2.1
  photo_view: ^0.15.0
  intl: ^0.19.0
  share_plus: ^7.2.1
  path_provider: ^2.1.1
  video_thumbnail: ^0.5.3
  flutter_native_splash: ^2.4.4
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9
  async: ^2.11.0
  dio: ^5.4.0
  video_player: ^2.5.1
  flutter_local_notifications: ^17.1.2
  google_fonts: ^6.2.1
  pretty_animated_text: ^2.0.0
  file_picker: ^10.3.1
  pdfx: ^2.9.2
  local_auth: ^2.1.7
  mockito: ^5.5.1
  build_runner: ^2.10.2
  adaptive_platform_ui: ^0.1.100
  extended_image: ^10.0.1
  verification_code_field: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - riv_assets/fillfolder.riv
    - riv_assets/emptyfolder.riv
    - riv_assets/nowifi.riv
    - assets/SplashScreenImg.png
    - assets/SplashScreenFirstBig.png
    - assets/hello-hi.gif
    - .env
